Locacao/Locacao/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Locacao.Models;
using Locacao.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Locacao.Controllers
{



    public class ReservaController : Controller
    {
        private readonly IReservaRepository reservaRepository;
        private readonly IUsuarioRepository usuarioRepository;
        private readonly IPedidoRepository pedidoRepository;
        private readonly IVeiculoRepository veiculoRepository;
        private readonly IStatusPedidoRepository statusPedidoRepository;



        public ReservaController(IUsuarioRepository usuarioRepository, IReservaRepository reservaRepository, IPedidoRepository pedidoRepository, IVeiculoRepository veiculoRepository,
    IStatusPedidoRepository statusPedidoRepository)
        {
            this.usuarioRepository = usuarioRepository;
            this.reservaRepository = reservaRepository;
            this.pedidoRepository = pedidoRepository;
            this.veiculoRepository = veiculoRepository;
            this.statusPedidoRepository = statusPedidoRepository;

        }


        public IActionResult Index()
        {
            var Adm = usuarioRepository.GetUsuarioLogado();
            if (!Adm.Administrador)
            {
                var lista = reservaRepository.BuscaListaReserva(Adm.Id);
                return View(lista);
            }
            else
            {
                var lista = reservaRepository.BuscaListaReserva();
                return View(lista);
            }
            
           
        }

        public IActionResult Reservar(int Id)
        {
            var UsuarioLogado = usuarioRepository.GetUsuarioLogado();
            var VeiculoSelecionado = veiculoRepository.GetVeiculoId(Id);
            var reserva = new Reserva();
            reserva.DataReserva = DateTime.Now;
            reserva.usuario = UsuarioLogado;
            reserva.Veiculo = VeiculoSelecionado;
            reserva.StatusPedido = statusPedidoRepository.GetstatusId(1);
             reservaRepository.SaveReserva(reserva);
            
            return View(reserva);
        }

        public IActionResult GeraPedido(int Id)
        {
            
            var reservaselecionada = reservaRepository.BuscaReservaId(Id);

            reservaselecionada.StatusPedido = statusPedidoRepository.GetstatusId(2);

            reservaRepository.SaveReserva(reservaselecionada);
            
            var NewPedido = new Pedido(reservaselecionada,DateTime.Now,DateTime.Now,Convert.ToDecimal(0),statusPedidoRepository.GetstatusId(1));

            var sucesso = pedidoRepository.SavePedido(NewPedido);

            ViewBag.Titulo = "Pedido Realizado";
            return View(sucesso);
        }

        public IActionResult GGeraPedido(Pedido Pedido)
        {
         
            ViewBag.Titulo = "Pedido Fechado";
            return View(Pedido);
        }

    }
}

Locacao/Locacao/Views/Reserva/GeraPedido.cshtml
@{
    ViewData["Title"] = "GeraPedido";
    Layout = "~/Views/Shared/LayoutLogado.cshtml";
}
@model Pedido
<h1>@ViewBag.Titulo</h1>
<br />


    <table class="table">
        <thead>
            <tr>
                <th scope="col">IdPedido</th>
                <th scope="col">Data do Pedido</th>
                <th scope="col">Status</th>
                
            </tr>
        </thead>
        <tbody>
                           
            <tr>
                <td>@Model.Id</td>
                <td>@Model.DataRetirada</td>
                <td>
                    @Model.Status.Descricao

                </td>
                <td>
                    <div class="text-center">
                        <a id="FechaRsv" asp-controller="Reserva" asp-action="Index"
                           
                           class="btn btn-success">Retornar</a>
                    </div>
                </td>

            </tr>
            
        </tbody>
    </table>


@section Scripts{
    <script type="text/javascript">


        $('#Header').hide();

    </script>
}

Locacao/Locacao/Views/Reserva/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutLogado.cshtml";
}
@model List<Reserva>
<h1>Lista Reservas</h1>
<br />

@if (Model != null && Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Data Reserva</th>
                <th scope="col">Usuario</th>
                <th scope="col">Veiculo</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @{
                var t = 0;
            }
            @foreach (var i in Model)

            {
                t++;
            <tr>
                <td>@t</td>
                <td>@i.DataReserva</td>
                <td>
                    @i.usuario.Nome

                </td>
                <td>@i.Veiculo.Marca</td>
                <td>@i.StatusPedido.Descricao</td>
                @if (i.StatusPedido.Id == 1)
                {
                    <td>
                        <div class="text-center">
                            <a id="FechaRsv" asp-controller="Reserva" asp-action="GeraPedido"
                               asp-route-id="@i.Id"
                               class="btn btn-success">Confirmar Reserva</a>
                        </div>
                    </td>
                }
                <td>
                    
                    
                </td>


            </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Nenhuma Reserva Encontrada</p>
}

@section Scripts{
    <script type="text/javascript">

        $.ajax({
            url: '/Login/ValidaAdm',
            method: 'Get',
            contentType: 'application/json',

            beforeSend: function () {
                //$("#resultado").html("ENVIANDO...");
            }
        })
            .done(function (msg) {
                debugger;
                if (msg) {
                    $('#FechaPdo,#FechaRsv,#AltUser,#Pedidos').removeAttr('hidden');
                    $('#Nm').html('Pedidos');
                }
                else {
                    $('#FechaPdo,#FechaRsv,#AltUser,#Pedidos').attr('hidden', 'true');
                     $('#Nm').html('Meus Pedidos');
                    debugger;
                }
            })
            .fail(function (jqXHR, textStatus, msg) {
                alert(msg);
            });


    </script>
}

Locacao/Locacao/Views/Reserva/Reservar.cshtml
@{
    ViewData["Title"] = "Reservar";
    Layout = "~/Views/Shared/LayoutLogado.cshtml";
}

@model Reserva
<h1>Reserva Realizada</h1>

<br />

<h1>Usar Protocolo Para retirar Veículo</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Protocolo Id</th>
            <th scope="col">Data do Reserva</th>
            <th scope="col">Modelo Veículo</th>
            <th scope="col">Status</th>

        </tr>
    </thead>
    <tbody>

        <tr>
            <td>@Model.Id</td>
            <td>@Model.DataReserva</td>
            <td>@Model.Veiculo.Modelo</td>
            <td>
                @Model.StatusPedido.Descricao

            </td>
            <td>
                <div class="text-center">
                    <a id="FechaRsv" asp-controller="Reserva" asp-action="Index"
                       class="btn btn-success">Retornar</a>
                </div>
            </td>

        </tr>

    </tbody>
</table>


@section Scripts{
    <script type="text/javascript">

        $.ajax({
            url: '/Login/ValidaAdm',
            method: 'Get',
            contentType: 'application/json',

            beforeSend: function () {
                //$("#resultado").html("ENVIANDO...");
            }
        })
            .done(function (msg) {
                debugger;
                if (msg) {
                    $('#FechaPdo,#FechaRsv,#AltUser,#Pedidos').removeAttr('hidden');
                    $('#Nm').html('Pedidos');
                }
                else {
                    $('#FechaPdo,#FechaRsv,#AltUser,#Pedidos').attr('hidden', 'true');
                    $('#Nm').html('Meus Pedidos');
                    debugger;
                }
            })
            .fail(function (jqXHR, textStatus, msg) {
                alert(msg);
            });


    </script>
}